Create ansible role Certbot
claranet/ansible-role-certbot pull request #1
Opened 2021-12-10 16:16 UTC by lsaintier

2022-02-07 09:42 UTC, geetoodeetoo commented
@ElieDeloumeau  we need a review ;-)

2022-02-07 10:18 UTC, ElieDeloumeau requested changes
Could you please test it on Ubuntu, CentOS and AmazonLinux? I think it can work as is

2022-02-07 10:18 UTC, ElieDeloumeau commented on vars/main.yml
> +ansible_distro_major_version: "{{ ansible_distribution_major_version|lower|replace('/', '_') }}"
These variables are not used, you should remove this file

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/create-cert-webroot.yml
> +  register: letsencrypt_cert
```suggestion
  register: _certbot_letsencrypt_cert
```

Private variables should be prefixed with `_certbot_`

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/create-cert-webroot.yml
> +  register: generate_certificate
```suggestion
  register: _certbot_generate_certificate
```

Private variables should be prefixed with `_certbot_`

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/create-cert-webroot.yml
> +  when: generate_certificate.changed
```suggestion
  when: _certbot_generate_certificate.changed
```

Private variables should be prefixed with `_certbot_`

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/main.yml
> +
```suggestion
```

This code is not used, so you can should delete it

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/main.yml
> +    loop_var: cert_item
```suggestion
    loop_var: _certbot_cert_item
```

Private variables should be prefixed with `_certbot_`

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/create-cert-webroot.yml
> +    path: /etc/letsencrypt/live/{{ cert_item.domains | first }}/cert.pem
```suggestion
    path: /etc/letsencrypt/live/{{ _certbot_cert_item.domains | first }}/cert.pem
```

Private variables should be prefixed with `_certbot_`

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/create-cert-webroot.yml
> +    path: "{{ cert_item.webroot | default(certbot_webroot) }}"
```suggestion
    path: "{{ _certbot_cert_item.webroot | default(certbot_webroot) }}"
```

Private variables should be prefixed with `_certbot_`

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/install-certbot.yml
> +  loop: "{{ certbot_packages }}"
```suggestion
- name: Install Certbot from repository and related packages
  package:
    name: "{{ certbot_packages }}"
    state: "present"
```

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/install-certbot.yml
> +  loop: "{{ certbot_plugins }}"
```suggestion
- name: Install Certbot plugins
  pip:
    name: "{{ certbot_plugins }}"
```

2022-02-07 10:18 UTC, ElieDeloumeau commented on tasks/install-certbot.yml
> +  apt: name=cron state=present
```suggestion
- name: Install cron
  package:
    name: cron
    state: present
```

Non OS specific task

2022-02-11 10:34 UTC, rsicart commented
> Could you please test it on Ubuntu, CentOS and AmazonLinux? I think it can work as is

Ubuntu is OK, but for CentOS and AmazonLinux there's more work to do.

Perhaps we can remove CentOS 8 from tests https://github.com/ansible-collections/news-for-maintainers/discussions/4 ?

2022-02-15 13:09 UTC, ElieDeloumeau commented
> Perhaps we can remove CentOS 8 from tests [ansible-collections/news-for-maintainers#4](https://github.com/ansible-collections/news-for-maintainers/discussions/4) ?

CentOS was to validate the RHEL compatibility but indeed we need to replace this test with [UBI](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) later.

We can skip the compatibility with RHEL and AmazonLinux for now, I'll create a new PR later.

2022-02-18 10:01 UTC, ElieDeloumeau approved these changes

2022-02-18 10:03 UTC, merged